# Generated by Django 4.0.3 on 2025-10-22 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer_portal', '0004_vehicle_alter_cardealer_area_alter_vehicles_dealer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_portal', '0006_auto_20180406_0520'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_address', models.CharField(max_length=255)),
                ('rental_date', models.DateField()),
                ('return_date', models.DateField()),
                ('total_days', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_image', models.ImageField(upload_to='payment_uploads/')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_dealer_portal.vehicles')),
            ],
        ),
    ]
