# Generated by Django 4.0.3 on 2025-10-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0007_rentaldetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentaldetails',
            name='payment_image',
        ),
        migrations.RemoveField(
            model_name='rentaldetails',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='rentaldetails',
            name='user',
        ),
        migrations.AddField(
            model_name='rentaldetails',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='rentaldetails',
            name='rent',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentaldetails',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='rentaldetails',
            name='customer_name',
            field=models.CharField(max_length=255),
        ),
    ]
