# Generated by Django 4.0.3 on 2025-10-22 05:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer_portal', '0003_vehicles_image_vehicles_price_per_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('description', models.TextField()),
                ('pincode', models.CharField(max_length=10)),
                ('category', models.CharField(choices=[('FAMILY', 'Family'), ('VAN', 'Van'), ('BUSINESS', 'Business & Professional'), ('WEDDING', 'Wedding')], max_length=20)),
                ('image', models.ImageField(upload_to='vehicles/')),
                ('upload_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='cardealer',
            name='area',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='car_dealer_portal.area'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_dealer_portal.cardealer'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='image',
            field=models.ImageField(default='no_image.jpg', upload_to='vehicles/'),
            preserve_default=False,
        ),
    ]
